# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
  favicon: "/img/favicon.png"
  high_res_favicon: "/img/favicon.png"
  keywords:
  site_verification:
    google:
    baidu:

# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Theme Color
color:
  android_chrome_color: "#0097A7"

# ---------------------------------------------------------------
# Customsize Settings
# ---------------------------------------------------------------

# Jump Links Settings
url:
  rss:
  daily_pic: "https://www.itypen.com"
  logo: "https://www.itypen.com"

# Images Settings
img:
  logo: "/img/logo.jpg"
  avatar: "/img/avatar.jpg"
  daily_pic: "/img/daily_pic.png"
  random_thumbnail: "/img/rondom/material-"

# Thumbnail Settings
thumbnail:
    purecolor:
    random_amount: 19

# Slogan (will show at daily_pic)
slogan: "Hi, nice to meet you"

# Posts Settings
post:
    entry_excerpt: 80

    # Qrcode for redirect at other device
    #    use: choose which method to generate the qrcode for each posts.
    #        Available value: plugin | online
    #            - When use "plugin", you need to install the hexo-helper-qrcode.
    #            - When use "online", the qrcode will be generated by 'pan.baidu.com' in Mainland China,
    #               and generated by 'charts.googleapis.com' in other areas.
    qrcode:
      enable: false
      use: plugin

    # Post License
    # You can specify the text you want to show in the end of your posts and pages, HTML tag is supported.
    #   For example, you can setup a CC license as:
    #       'This blog is under a <a href="/creativecommons.html" target="_blank">CC BY-NC-SA 3.0 Unported License</a>'
    # You can also use Front-Matter `license` to override this setting.
    license: 

    # TOC Button
    toc:
    # use: choose whether the line_number of toc will show or not.
    #   Available value of "linenumber": true | false
      linenumber: true

# Footer Settings
footer:
  # Footer Copyright
  # Specify the date when the site was setup.
  #    For example, if you set it as 2015, then footer will show '© 2015 - 2017'
  copyright_since: iTypen © 2015 - 2019

  # FooterSNS Icon
  sns:
    facebook: "https://www.facebook.com/facebook"
    twitter: "https://twitter.com/twitter"
    googleplus: "https://www.google.com/"
    weibo: https://weibo.com/stark2chen
    instagram:
    tumblr:
    github:
    linkedin:
    zhihu:
    bilibili:
    telegram:
    v2ex:

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# SNS Share Switch
sns_share:
  twitter: true
  facebook: true
  googleplus: true
  weibo: true
  linkedin: false
  qq: false
  telegram: false

# Sidebar Customize
sidebar:
  homepage:
    use: true
    icon: home
    divider: false
  archives:
    use: true
    icon: inbox
    divider: false
  pages:
    友情链接:
      link: "/links"
      icon: person
      divider: false
    #About:
      #link: "/about"
      #icon: person
      #divider: false
  article_num:
    use: true
    divider: true
  footer:
    upyun_logo:
      link: "https://www.upyun.com/"
      src: "/img/upyun_logo.svg"


# ---------------------------------------------------------------
# Integrated Services
# ---------------------------------------------------------------

# Comment Systems
# Available value of "use":
#   disqus | disqus_click | changyan | livere | gitment | valine
# If you want to use gitment,you should get the client_id and client_secret form https://github.com/settings/applications/new
# If you want to use valine,you should get the app_id and app_key form https://leancloud.cn ,more setting please see https://github.com/xCss/Valine
comment:
  use:
  shortname: # duoshuo or disqus shortname
  changyan_appid:
  changyan_conf:
  changyan_thread_key_type: path
  livere_data_uid:
  gitment_repo:   # git repo of the hexo
  gitment_owner:  # git repo's owner
  gitment_client_id:  # github app client id 
  gitment_client_secret :  # github app client secret 
  valine_leancloud_appId: # leancloud application app id
  valine_leancloud_appKey: # leancloud application app key

# Analytics Systems
# Available value:
#     baidu | google | cnzz
analytics:
  google_site_id: UA-123878647-1
  baidu_site_id:
  cnzz_site_id:

# Search Systems
search:
  use: false # true || false
  link: 

# ---------------------------------------------------------------
# Do Not Edit Below This Line, unless you know what you are doing!
# ---------------------------------------------------------------
verison: 0.1.1
old_verison:
  - 0.1.0
