language: node_js
dist: trusty
node_js:
  - "8"
install:
  - npm install
script:
  - npm run clean
  - npm run generate
  - chmod +x ./deploy.sh
  - \cp -f assets/CNAME public/CNAME
  - \cp -f assets/analytics.txt public/analytics.txt
  - \cp -f assets/googlef15886275820ed2b.html public/googlef15886275820ed2b.html
  - \cp -f assets/sogousiteverification.txt public/sogousiteverification.txt
  - ./deploy.sh > /dev/null
  - npm run clean
cache:
  directories:
    - node_modules