language: node_js
dist: trusty
cache:
  directories:
    - node_modules
node_js:
  - "10"
install:
  - npm install
  - npm audit fix
script:
  - npm run clean
  - npm run generate
  - chmod +x ./deploy.sh
  - \cp -f assets/CNAME public/CNAME
  - ./deploy.sh > /dev/null
  - npm run clean
cache:
  directories:
    - node_modules
notifications:
  webhooks:
    urls:
      - https://open.feishu.cn/officialapp/notify/7981457d0f1711ee9149ab8157c3ed923fe18c886f9d16af1166aa713c70d287
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always