language: node_js
dist: trusty
cache:
  directories:
    - node_modules
node_js:
  - "10"
install:
  - npm install
script:
  - npm run clean
  - npm run generate
  - chmod +x ./deploy.sh
  - \cp -f assets/CNAME public/CNAME
  - ./deploy.sh > /dev/null
  - npm run clean
cache:
  directories:
    - node_modules