language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install

before_script:
 # - npm install -g gulp


script:
  - hexo clean && hexo g


after_script:
  - cd ./public
  - git init
  - git config user.name "Your GitHub User Name"
  - git config user.email "Your GitHub Email"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - master
    # - hexo
env:
 global:
   - GH_REF: github.com/USERNAME/USERNAME.github.io.git
