# ---------------------------------------------------------------
# ICON Settings
# ---------------------------------------------------------------

favicon: https://imgur.itypen.com/picgo/typelogo.png_avatar
avatar: https://imgur.itypen.com/picgo/gff.jpg
apple_icon:
  # iPhone 57x57 
  iphone: https://imgur.itypen.com/picgo/20190625163454.jpg_iPhone
  # iPad 72x72
  ipad: https://imgur.itypen.com/picgo/20190625163454.jpg_RetinaiPad
  # Retina iPhone 114x114
  iphone_hd: https://imgur.itypen.com/picgo/20190625163454.jpg_iPhoneHD
  # Retina iPad 144x144
  ipad_hd: https://imgur.itypen.com/picgo/20190625163454.jpg_RetinaiPad
  
# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Schemes
schemes: column

# ---------------------------------------------------------------
# Header and Aside Settings
# ---------------------------------------------------------------

# Header
# style default | card
header: 
  style: card
  img: https://imgur.itypen.com/picgo/20200201164712.jpg_itp

drawer_header: https://imgur.itypen.com/picgo/20190529224135.jpg_itp

# Materiac ICON from https://www.mdui.org/docs/material_icon

# Header link
nav:
  关于:
    link: /about.html
    icon: person
  相册:
    link: /gallery/
    icon: photo
  搜索: 
    link: /search.html
    icon: search
    color: '#2196F3'

# Aside link
aside:
  首页: 
    link: /
    color: '#2196F3'
    icon: home
  归档: 
    link: /archives/
    icon:   move_to_inbox
    color: '#2196F3'
  友链:
    link: /links.html
    icon: link
    color: '#2196F3'

# ---------------------------------------------------------------
# Footer Settings
# ---------------------------------------------------------------

# about
start_time: 2016
footer: 永远相信美好的事情即将发生<br><div class="padding-15"></div><a href="https://travis-ci.org/aiokr/iTypen-Hexo" target="_blank">渲染状态</a>&nbsp;&nbsp;<a href="https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fblog.itypen.com%2F&tab=desktop" target="_blank">速度测试</a>
# info
count: true
busuanzi: true
# ICP
icp: 桂ICP备17001361号
# CDN
# Use upyun
cdn: 
  use: upyun
  upyun: 
    src: https://imgur.itypen.com/picgo/20190506220004.png_itp

# ---------------------------------------------------------------
# Posts Settings
# ---------------------------------------------------------------

# Post
default_post_title: Untitled
auto_excerpt:
  length: 120

# highlight.js
# style github | tomorrow | night | night-blue | night-bright | night-eighties
highlight:
  use: true
  style: night

# Comment
# Use gitment | valine | disqus | disqusjs
comment:
  use: disqusjs
  gitment:
    owner:
    repo:
    client_id:
    client_secret:
  valine:
    appid: 0kSi0u9r40XN3MswJG34Sj6K-gzGzoHsz
    appkey: 0etVoCn0nhOS5RSYOenq0sl6
  disqus:
    src: 
    # such as: https://xxx.disqus.com/embed.js
  disqusjs:
    shortname: itpnblog
    siteName: aiokr's blog
    api: https://disqus-proxy.disqusapi.workers.dev/api/
    apikey: ACUkOYE4R9hPhjn287JNMXWzlvdAGpIKLH4Kn8AITuclBETPKnU2j996mGXXxgnD
    admin: aiokr
    adminLabel: 站长

# Random Pictures
random_pics: 24

# ---------------------------------------------------------------
# Third Party Services Settings
# ---------------------------------------------------------------

# Google Analytics
google_analytics: UA-141010711-2

# ---------------------------------------------------------------
# Gallery Page Settings
# ---------------------------------------------------------------

gallery:
  title: 镜头记录下的是光明
  descr_title: 镜头记录下的是光明
  descr: 我们常常在繁杂和污浊中寻找光明，企图用光明照亮黑暗。殊不知光明的力量弱小，而黑暗则会吸收光芒。