# ---------------------------------------------------------------
# ICON Settings 图标设置
# ---------------------------------------------------------------

favicon: https://imgur.lzmun.com/picgo/after2022/presslogo.png_avatar
avatar: https://imgur.lzmun.com/picgo/after2022/presslogo.png_itp
apple_icon:
  # iPhone 57x57 
  iphone: https://imgur.lzmun.com/picgo/after2022/presslogo.png_iPhone
  # iPad 72x72
  ipad: https://imgur.lzmun.com/picgo/after2022/presslogo.png_RetinaiPad
  # Retina iPhone 114x114
  iphone_hd: https://imgur.lzmun.com/picgo/after2022/presslogo.png_iPhoneHD
  # Retina iPad 144x144
  ipad_hd: https://imgur.lzmun.com/picgo/after2022/presslogo.png_RetinaiPad
  
# ---------------------------------------------------------------
# Style Settings 样式设置
# ---------------------------------------------------------------

# Schemes
# Use column ｜ m3
schemes: m3

# Fonts
# Use LXGW ｜ 
fonts: LXGW


# Random Pictures
random_pic_switch: false
random_pics: 19
random_thumbnail: https://cdn.jsdelivr.net/gh/aiokr/hexo-theme-type-random_pics@v1.0.0/randompic-
# random_thumbnail: ../img/random/randompic-

# ---------------------------------------------------------------
# Header and Nav Settings 页眉、导航和封面设置
# ---------------------------------------------------------------

# Header Cover
header: 
  img: https://imgur.lzmun.com/picgo/after2022/Photo_6553646_DJI_46_jpg_4736772_0_2021414122720_photo_original.jpg_itp

# drawer_header: //imgur.lzmun.com/picgo/20200405182517.jpg
# drawer was removed

# Header Links
# icon list: https://fonts.google.com/icons?selected=Material+Icons&icon.style=Outlined
search_btn: true
nav:
  归档: 
    link: /archives/
    icon:  move_to_inbox
  相册:
    link: /gallery/
    icon: image
  关于:
    link: /about/
    icon: person

# Cover Links
cover_links:
  - title: Unsplash
    link: https://unsplash.com/@aiokr
    avatar: https://imgur.lzmun.com/picgo/20200323114326.jpg
    descr: '@aiokr'
  - title: 500px
    link: https://500px.com/vcg-aiokr
    avatar: https://imgur.lzmun.com/picgo/20200323114235.jpg
    descr: 'aiokr'
  - title: RSS Feed
    link: /atom.xml
    avatar: https://imgur.lzmun.com/2021/09/19/512x512bb.jpeg_itp
    descr: 'iTypen.APP'

# Materiac ICON from https://www.mdui.org/docs/material_icon

# ---------------------------------------------------------------
# Footer Settings 页脚设置
# ---------------------------------------------------------------

start_time: 2016
# 'count' need run 'npm install hexo-symbols-count-time --save'
count: true
icp: 

# CDN LOGO
# Use upyun
cdn: 
  use: 
  upyun: 
    src: 

# ---------------------------------------------------------------
# Index Settings 首页设置
# ---------------------------------------------------------------

# Social link 社交链接
social_link:
  # 
  use: true
  # 在这里开启微信二维码
  wechat_personal: 
    switch: false
    src: https://imgur.lzmun.com/picgo/20200324090429.jpg
  wechat_public: 
    switch: true
    src: https://open.weixin.qq.com/qr/code?username=itypen

# 订阅链接
subscription_link:
  use: false

# ---------------------------------------------------------------
# Posts Settings 文章设置
# ---------------------------------------------------------------

# Post
default_post_title: Untitled
auto_excerpt:
  length: 120

# highlight.js 代码高亮
# style github | tomorrow  | night-blue | night-bright | night-eighties
highlight:
  use: true
  style: night-eighties

# ---------------------------------------------------------------
# Third Party Services Settings 第三方服务设置
# ---------------------------------------------------------------

# Comment 评论
# Use gitment | valine | disqus | disqusjs | gitalk | waline
# disqusjs 参考 https://github.com/SukkaW/DisqusJS 进行部署
comment:
  use: waline
  gitment:
    owner:
    repo:
    client_id:
    client_secret:
  valine:
    appid: 
    appkey: 
  disqus:
    src: 
    # such as: https://xxx.disqus.com/embed.js
  disqusjs:
    shortname: 
    siteName: 
    api: 
    apikey: 
    title: 
    admin: 
  gitalk:
    clientID: 
    clientSecret: 
    repo: 
    owner: 
    admin: 
    distractionFreeMode: 
  waline:
    serverurl: https://waline-server-repo.vercel.app/

# Busuanzi Count 不蒜子计数
busuanzi: false

# Google Analytics 谷歌分析
# cloudflare-workers-async-google-analytics
# if use is default, it will use analytics.js
# if use is cf_async, look at the https://github.com/SukkaW/cloudflare-workers-async-google-analytics to learn more
# 如果 use 项选择 default，将使用 analytics.js 文件接入谷歌分析
# 如果 use 项目选择 cf_async，请浏览 https://github.com/SukkaW/cloudflare-workers-async-google-analytics 进行配置

google_analytics:
  # use: default
  use: cf_async
  ga_id: UA-141010711-2
  ga_api: https://async-google-analytics.disqusapi.workers.dev/

# chart.js
# https://www.chartjs.org/
chart_js:
  use: false