# basic
title: iTypen
subtitle: 
favicon: https://imgur.itypen.com/picgo/20190626220507.png_avatar
avatar: https://imgur.itypen.com/picgo/gff.jpg
drawer_header: https://imgur.itypen.com/picgo/20190529224135.jpg_itp

highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# nav #
nav:
  首页: 
    link: /
    color: '#2196F3'
    icon: home
  搜索: 
    link: /search.html
    icon: search
    color: '#2196F3'
  归档: 
    link: /archives/
    icon:   move_to_inbox
    color: '#2196F3'
  关于: 
    link: /about.html
    icon: person
    color: '#2196F3'
  友链:
    link: /links.html
    icon: link
    color: '#2196F3'
  渊梦:
    link: 'https://www.itypen.com'
    icon: insert_photo
    color: '#2196F3'
  # rss: atom.xml

# hexo-renderer-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

# Default post title
default_post_title: Untitled

auto_excerpt:
  length: 120

footer: Powered by <a href="https://hexo.io/" target="_blank">Hexo</a>

comment:
  use: disqusjs
  gitment:
    owner:
    repo:
    client_id:
    client_secret:
  valine:
    appid:
    appkey:
  disqus:
    src: 
    # such as: https://xxx.disqus.com/embed.js
  disqusjs:
    shortname: itpnblog
    siteName: aiokr's blog
    api: https://disqus-proxy.disqusapi.workers.dev/api/
    apikey: ACUkOYE4R9hPhjn287JNMXWzlvdAGpIKLH4Kn8AITuclBETPKnU2j996mGXXxgnD
    admin: aiokr
    adminLabel: 站长

random_pics: 24