# basic
title: iTypen
subtitle: Minimalism, simplicity and refined details
favicon: https://imgur.itypen.com/picgo/144.png

avatar: https://imgur.itypen.com/picgo/512.png
banner_small: https://imgur.itypen.com/picgo/512.png
# banner_large: https://imgur.itypen.com/picgo/512.png
logo: https://imgur.itypen.com/picgo/512.png

# disqus
#disqus_shortname: drakeleung

highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# nav #
nav:
  首页: 
    link: /
    color: '#2196F3'
    icon: home
    
  搜索: 
    link: /search/
    icon: search
    color: '#2196F3'
  归档: 
    link: /archives/
    icon:   move_to_inbox
    color: '#2196F3'
  关于: 
    link: /about/
    icon: person
    color: '#2196F3'
  友链:
    link: /links/
    icon: link
    color: '#2196F3'
  作品:
    link: /work/
    icon: insert_photo
    color: '#2196F3'
  # rss: atom.xml

# hexo-renderer-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

# Default post title
default_post_title: Untitled

# social
social:
  github: https://github.com/aiokr
  # weibo: http://weibo.com/10010800
  # mail: mailto:gallenhu@foxmail.com
  # twitter: https://twitter.com/GallenHu

# widget
#   title: 标题
#   content: 内容
widget:
  title: 关于本站
  content: 寻找是唯一的解药

footer: Powered by <a href="https://hexo.io/" target="_blank">Hexo</a> with Theme <a href="https://github.com/GallenHu/hexo-theme-Daily" target="_blank">Daily</a>

comment:
  use: valine
  gitment:
    owner: aiokr
    repo: iTypen-comment
    client_id: 53d9f4220507e8aa513b
    client_secret: 43e42209f73188b31e4ae88a7882b1cbc51fc764
  valine:
    appid: 0kSi0u9r40XN3MswJG34Sj6K-gzGzoHsz
    appkey: 0etVoCn0nhOS5RSYOenq0sl6

random_pics: 24