# basic
title: iTypen
subtitle: Minimalism, simplicity and refined details
favicon: https://imgur.itypen.com/picgo/144.png

avatar: https://imgur.itypen.com/picgo/512.png
banner_small: https://imgur.itypen.com/picgo/512.png
# banner_large: https://imgur.itypen.com/picgo/512.png
logo: https://imgur.itypen.com/picgo/512.png

# disqus
#disqus_shortname: drakeleung

highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# nav #
nav:
  归档: 
    link: /archives/
  关于: 
    link: /about/
  链接:
    link: /links/
  图库:
    link: /photograph/
  # rss: atom.xml

# hexo-renderer-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

# Default post title
default_post_title: Untitled

# social
social:
  github: https://github.com/aiokr
  # weibo: http://weibo.com/10010800
  # mail: mailto:gallenhu@foxmail.com
  # twitter: https://twitter.com/GallenHu

# widget
#   title: 标题
#   content: 内容
widget:
  title: 关于本站
  content: <ul><li><a href="https://github.com/GallenHu/hexo-theme-Daily/wiki">如何自定义这里的内容(配置教程)?</a></li></ul>

footer: Powered by <a href="https://hexo.io/" target="_blank">Hexo</a> with Theme <a href="https://github.com/GallenHu/hexo-theme-Daily" target="_blank">Daily</a>

comment:
  use: gitment
  gitment:
    owner: aiokr
    repo: iTypen-comment
    client_id: 53d9f4220507e8aa513b
    client_secret: 43e42209f73188b31e4ae88a7882b1cbc51fc764

random_pics: 24