name: Tripper-China-Pages

on:
  push

jobs:
  pages_generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: pacakge theme
      run: |
        sudo apt-get install tree
        sudo git config --global user.name "aiokr"
        sudo git config --global user.email "aiokr@outlook.com"
        sudo apt-get install tree
        sudo npm install
        sudo hexo g
        sudo cd public
        tree
        sudo git init 
        sudo git add -A
        sudo git commit -m "Generate Pages"
        sudo git push --force "https://${{secrets.gitee_key}}@gitee.com/aiokr/tripper-pages.git" master
        