name: iTypen.APP auto publish

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  - name: install
    runs-on: ubuntu-latest
    steps:
    - npm install
    - npm audit fix
  - name: hexo generate
    runs-on: ubuntu-latest
    steps:
    - npm run clean
    - npm run generate
  - name: publish
    runs-on: ubuntu-latest
    steps:
     - chmod +x ./deploy.sh
     - \cp -f assets/CNAME public/CNAME
     - ./deploy.sh > /dev/null