name: iTypen.APP auto publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publish_ITPN:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true # Checkout private submodules(themes or something else).
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: install_env
        run: npm install
      - name: hexo_generate
        run: |
          ls
          npm run clean
          npm run generate
      - name: hexo_publish
        run: |
          cd ./public
          git init
          git config --global push.default matching
          git_email
          git config --global user.email "hiaiokr@gmail.com"
          git config --global user.name "aiokr"
          git add --all .
          git commit -m "Auto Builder of aiokr's blog"
          git push --force "https://${{secrets.action_key}}@github.com/aiokr/iTypen-Pages.git" master