name: Sync Tripper Posts

on:
  push:
    paths:
      - 'source/_posts/**'
      - '.github/**'
jobs:
  sync_posts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: sync posts
      run: |
        sudo apt-get install tree
        cd source/_posts
        sudo git init
        sudo git config --global push.default matching
        sudo git config --global user.email "hiaiokr@gmail.com"
        sudo git config --global user.name "aiokr"
        sudo git add -A
        sudo git commit -m "Sync Posts by aiokr"
        sudo git push --force "https://${{secrets.action_key}}@github.com/aiokr/Tripper-Posts.git" master