name: Hexo-Theme-Type auto generate

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  theme_generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: list all files
      run: |
        ls