name: Hexo-Theme-Type auto generate

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  theme_generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: list all files
      run: |
        cd themes/hexo-theme-type
        ls
    - name: clear configuration files
      run: |
        import yaml
        class Yamlutil:
        def clear_yaml(self):
        with open(os.getcwd()+"/_config.yaml",mode='w',encoding='utf-8') as f:
            f.truncate()
    - name: package theme folder
      run: |
        git init
        git config --global push.default matching
        git config --global user.email "hiaiokr@gmail.com"
        git config --global user.name "aiokr"
        git add --all .
          git commit -m "Auto package by aiokr"
          git push --force "https://${{secrets.action_key}}@github.com/aiokr/hexo-theme-type.git" master