name: Hexo-Theme-Type auto generate

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  theme_generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: pacakge theme
      run: |
        cd themes/hexo-theme-type
        ls
        rm _config.yml
        ls
        git init
        git config --global push.default matching
        git config --global user.email "hiaiokr@gmail.com"
        git config --global user.name "aiokr"
        git add --all .
          git commit -m "Auto package by aiokr"
          git push --force "https://${{secrets.action_key}}@github.com/aiokr/hexo-theme-type.git" master