name: Hexo-Theme-Type auto generate

on:
  push:
    paths:
      - 'themes/**'
  pull_request:
    paths:
      - 'themes/**'

jobs:
  theme_generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: pacakge theme
      run: |
        sudo apt-get install tree
        cd themes/hexo-theme-type
        rm _config.yml
        cd ..
        mkdir package
        cd package
        git clone https://github.com/aiokr/hexo-theme-type.git
        echo [clone successed]
        cd hexo-theme-type
        echo [come into hexo theme git folder]
        sudo chmod -R 777 .git
        sudo cp -r .git ..
        sudo rm -rf *
        sudo rm -rf .git/index.lock
        echo [copy git files and clean folder]
        sudo rm -rf .git
        echo [clean git files in hexo theme git folder]
        cd ..
        echo [come into package folder]
        sudo cp -r .git hexo-theme-type
        echo [copy git files back]
        cd hexo-theme-type
        echo [come into theme folder]
        sudo git checkout auto-package
        echo [change branches]
        cd ../..
        echo [come into 'themes' folder]
        sudo cp -r hexo-theme-type package
        cd package
        cd hexo-theme-type
        rm -rf _config.yml
        tree
        sudo rm -rf .git/index.lock
        sudo git config --global push.default matching
        sudo git config --global user.email "hiaiokr@gmail.com"
        sudo git config --global user.name "aiokr"
        sudo git add -A
        sudo git commit -m "Auto package by aiokr"
        sudo git push --force "https://${{secrets.action_key}}@github.com/aiokr/hexo-theme-type.git" auto-package